### PR TITLE
fix: convert series_index to number when applicable

### LINKED ISSUE #42: series_index recorded as string causes crash when sorting by series
Currently, it seems the plugin records series_index as a string. This is an excerpt from the generated custom_metadata.lua file:
`        ["series_index"] = "1.0",
`

If I sort a folder by series and it contains a CBZ with metadata from the plugin, KOReader crashes with this in the crash log:
`./luajit: frontend/ui/widget/booklist.lua:230: attempt to compare string with number
`

It seems that KOReader is trying to compare the series_index with other indices in order to sort by series, but because the series_index is a string it fails and crashes. When changing back to another kind of sort, everything works properly.

This is happening in a folder which only contains other CBZ's which use this plugin for metadata, no other ebook filetypes are present in the folder.

If possible, could we record the series_index as an int so this behavior could be avoided?

Here is the complete crash log if it helps:
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/08/26-20:46:02
has monolibtic? no (libs/libkoreader-monolibtic.so: cannot open shared object file: No such file or directory)
lib_search_path: libs/?
lib_basic_format: lib%s.so
lib_version_format: lib%s.so.%s
 [*] Version: v2025.10

ffi.load: rt.so.1 (RTLD_GLOBAL)
ffi.findlib: utf8proc [3]
ffi.load: libs/libutf8proc.so.3
ffi.findlib: blitbuffer
ffi.load: libs/libblitbuffer.so
ffi.findlib: archive [13]
ffi.load: libs/libarchive.so.13
ffi.findlib: sqlite3 [0]
ffi.load: libs/libsqlite3.so.0
ffi.findlib: fbink_input [1]
ffi.load: libs/libfbink_input.so.1
[FBInk] /dev/input/event0: `bd71828-pwrkey` = KEY | POWER_BUTTON
[FBInk] /dev/input/event1: `pt_mt` = TOUCHSCREEN
[ko-input] Forked off fake event generator (pid: 12041)
01/08/26-20:46:03 INFO  initializing for device KindlePaperWhite5SE 
01/08/26-20:46:03 INFO  framebuffer resolution: {
  h = 1648,
  w = 1236
} --[[table: 0xb6823220]] 
ffi.findlib: wrap-mupdf
ffi.load: libs/libwrap-mupdf.so
ffi.findlib: freetype [6]
ffi.load: libs/libfreetype.so.6
ffi.findlib: harfbuzz [0]
ffi.load: libs/libharfbuzz.so.0
ffi.findlib: zstd [1]
ffi.load: libs/libzstd.so.1
01/08/26-20:46:05 INFO  Looking for plugins in directory: plugins 
ffi.findlib: leptonica [6]
ffi.load: libs/libleptonica.so.6
ffi.findlib: k2pdfopt [2]
ffi.load: libs/libk2pdfopt.so.2
./luajit: frontend/ui/widget/booklist.lua:230: attempt to compare string with number
stack traceback:
	frontend/ui/widget/booklist.lua:230: in function <frontend/ui/widget/booklist.lua:225>
	[C]: in function 'sort'
	frontend/ui/widget/filechooser.lua:246: in function 'genItemTableFromPath'
	frontend/ui/widget/filechooser.lua:325: in function 'refreshPath'
	frontend/ui/widget/filechooser.lua:349: in function 'changeToPath'
	frontend/ui/widget/filechooser.lua:394: in function 'onMenuSelect'
	plugins/coverbrowser.koplugin/mosaicmenu.lua:771: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:896: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1423: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1523: in function 'handleInput'
	frontend/ui/uimanager.lua:1567: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x00013ed5
lipc-wait-event exited normally with status: 0
```

### PR DESCRIPTION
**Pull request by OGKevin**
Ensure series_index is always a numeric value by converting the metadata.Number field using tonumber(). This prevents type mismatches when the series index is expected to be a number by downstream components.

- Convert series_index to numeric type in metadata mapping

Change-Id: 66cc22e8f7ce6acf5dca35b2d959e2d7
Change-Id-Short: ttnnxxlrksnl
Fixes: #42

### CODE REVIEW

File: main.lua [hunk 1]
```diff
@@ -74,7 +74,7 @@ function ComicMeta:processFile(comic_file)
         title = comicInfo.metadata.Title,
         authors = comicInfo.metadata.Writer,
         series = comicInfo.metadata.Series,
-        series_index = comicInfo.metadata.Number,
+        series_index = tonumber(comicInfo.metadata.Number),
```
Comment (Amelinyaa) [inline main.lua]:
```suggestion
        series_index = tonumber(comicInfo.metadata.Number) or comicInfo.metadata.Number,
```
This will convert to a number only when applicable, as `tonumber` returns `nil` otherwise

**Review by NightQuest — CHANGES_REQUESTED** [review]

**Review by NightQuest — APPROVED** [review]
perhaps change title before merge, appending `when applicable` to the end
